name: Build and Test

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the artifact containing build outputs"
        value: ${{ jobs.pack.outputs.artifact-name }}

jobs:
  pack:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: output-${{ github.run_number }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: ./build.ps1 --target=pack
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          include-hidden-files: true
          path: .output/
          retention-days: 1

  test:
    runs-on: ${{ matrix.os }}
    needs: [pack]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - uses: actions/download-artifact@v4
        with:
          name: output-${{ github.run_number }}-${{ github.run_attempt }}
          path: .output/

      - run: ./build.ps1 --target=test --exclusive
        shell: pwsh