name: NuGet push

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-test:
    uses: ./.github/workflows/_build-test.yml

  push:
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-test.outputs.artifact-name }}
          path: .output/

      - run: ./build.ps1 --target=push --exclusive --nuget-api-key=${{ secrets.NUGET_API_KEY }} --nuget-source=${{ secrets.NUGET_SOURCE }}
        shell: pwsh

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: ${{ needs.build-test.outputs.artifact-name }}